 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fundamentosproyectofinal;

import javax.swing.JOptionPane;

/**
 *
 * @author Karla
 */
public class InterfazRegistrarClientes extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarClientes
     */
    public InterfazRegistrarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UsuarioNuevoIDUsuarioTxt = new javax.swing.JTextField();
        UsuarioNuevoNombreTxt = new javax.swing.JTextField();
        UsuarioNuevoSegundoNombreTxt = new javax.swing.JTextField();
        UsuarioNuevoApellidoTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        UsuarioNuevoGeneroCbx = new javax.swing.JComboBox<>();
        UsuarioNuevoGuardarBtn = new javax.swing.JButton();
        UsuarioNuevoLimpiarCasillasBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        UsuarioNuevoTelefonoTxt = new javax.swing.JTextField();
        UsuarioNuevoTipoTelefonoCbx = new javax.swing.JComboBox<>();
        UsuarioNuevoProvinciaCbx = new javax.swing.JComboBox<>();
        UsuarioNuevoCiudadTxt = new javax.swing.JTextField();
        UsuarioNuevoDireccion1Txt = new javax.swing.JTextField();
        UsuarioNuevoDireccion2Txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        UsuarioNuevoEmailTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        UsuarioNuevoVolverAlMenuPrincipalBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setText("ID Usuario:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Segundo Nombre:");

        jLabel4.setText("Apellido:");

        UsuarioNuevoIDUsuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioNuevoIDUsuarioTxtActionPerformed(evt);
            }
        });

        UsuarioNuevoNombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioNuevoNombreTxtActionPerformed(evt);
            }
        });

        jLabel7.setText("Género:");

        UsuarioNuevoGeneroCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino", "Otro" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(UsuarioNuevoSegundoNombreTxt)
                            .addComponent(UsuarioNuevoGeneroCbx, 0, 140, Short.MAX_VALUE)
                            .addComponent(UsuarioNuevoIDUsuarioTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(UsuarioNuevoApellidoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(UsuarioNuevoNombreTxt))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioNuevoIDUsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioNuevoNombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioNuevoSegundoNombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioNuevoApellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsuarioNuevoGeneroCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        UsuarioNuevoGuardarBtn.setText("Guardar");
        UsuarioNuevoGuardarBtn.setToolTipText("");
        UsuarioNuevoGuardarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuarioNuevoGuardarBtnMouseClicked(evt);
            }
        });
        UsuarioNuevoGuardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioNuevoGuardarBtnActionPerformed(evt);
            }
        });

        UsuarioNuevoLimpiarCasillasBtn.setText("Limpiar casillas");
        UsuarioNuevoLimpiarCasillasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuarioNuevoLimpiarCasillasBtnMouseClicked(evt);
            }
        });
        UsuarioNuevoLimpiarCasillasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioNuevoLimpiarCasillasBtnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de contacto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel5.setText("Teléfono");

        jLabel6.setText("Tipo de teléfono:");

        jLabel8.setText("Provincia:");

        jLabel9.setText("Ciudad");

        jLabel10.setText("Dirección1:");

        jLabel11.setText("Dirección 2:");

        UsuarioNuevoTelefonoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioNuevoTelefonoTxtActionPerformed(evt);
            }
        });

        UsuarioNuevoTipoTelefonoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celular", "Hogar", "Oficina", "Otro" }));

        UsuarioNuevoProvinciaCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San José", "Alajuela", "Heredia", "Cartago", "Limón", "Puntarenas", "Guanacaste" }));

        UsuarioNuevoCiudadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioNuevoCiudadTxtActionPerformed(evt);
            }
        });

        jLabel12.setText("E-mail:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(UsuarioNuevoTelefonoTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(UsuarioNuevoProvinciaCbx, javax.swing.GroupLayout.Alignment.LEADING, 0, 149, Short.MAX_VALUE)
                        .addComponent(UsuarioNuevoDireccion1Txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(UsuarioNuevoEmailTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsuarioNuevoCiudadTxt)
                    .addComponent(UsuarioNuevoDireccion2Txt)
                    .addComponent(UsuarioNuevoTipoTelefonoCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioNuevoTelefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioNuevoTipoTelefonoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioNuevoProvinciaCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioNuevoCiudadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioNuevoDireccion1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioNuevoDireccion2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsuarioNuevoEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("USUARIO NUEVO");

        UsuarioNuevoVolverAlMenuPrincipalBtn.setText("Volver al menú principal");
        UsuarioNuevoVolverAlMenuPrincipalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuarioNuevoVolverAlMenuPrincipalBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(120, 120, 120))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(UsuarioNuevoGuardarBtn)
                                .addGap(18, 18, 18)
                                .addComponent(UsuarioNuevoLimpiarCasillasBtn)
                                .addGap(18, 18, 18)
                                .addComponent(UsuarioNuevoVolverAlMenuPrincipalBtn)
                                .addContainerGap())))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {UsuarioNuevoGuardarBtn, UsuarioNuevoLimpiarCasillasBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioNuevoGuardarBtn)
                    .addComponent(UsuarioNuevoLimpiarCasillasBtn)
                    .addComponent(UsuarioNuevoVolverAlMenuPrincipalBtn)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {UsuarioNuevoGuardarBtn, UsuarioNuevoLimpiarCasillasBtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioNuevoLimpiarCasillasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioNuevoLimpiarCasillasBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioNuevoLimpiarCasillasBtnActionPerformed

    private void UsuarioNuevoTelefonoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioNuevoTelefonoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioNuevoTelefonoTxtActionPerformed

    private void UsuarioNuevoIDUsuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioNuevoIDUsuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioNuevoIDUsuarioTxtActionPerformed

    private void UsuarioNuevoNombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioNuevoNombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioNuevoNombreTxtActionPerformed

    private void UsuarioNuevoCiudadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioNuevoCiudadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioNuevoCiudadTxtActionPerformed

    private void UsuarioNuevoVolverAlMenuPrincipalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioNuevoVolverAlMenuPrincipalBtnMouseClicked
          // con este codigo volvemos al menu principal y cerramos la ventana actual
        InterfazMenuPrincipal menuPrincipal= new  InterfazMenuPrincipal();
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UsuarioNuevoVolverAlMenuPrincipalBtnMouseClicked

    private void UsuarioNuevoGuardarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioNuevoGuardarBtnMouseClicked
        //Dentro de guardar es que validamos todos los datos que el cliente ingresó y los guardamos.
        String nombre = UsuarioNuevoNombreTxt.getText();
        String segundoNombre= UsuarioNuevoSegundoNombreTxt.getText();
        String apellido= UsuarioNuevoApellidoTxt.getText();
        String genero= UsuarioNuevoGeneroCbx.getItemAt(UsuarioNuevoGeneroCbx.getSelectedIndex());
        String tipoTelefono=  UsuarioNuevoTipoTelefonoCbx.getItemAt(UsuarioNuevoTipoTelefonoCbx.getSelectedIndex());
        String provincia= UsuarioNuevoProvinciaCbx.getItemAt(UsuarioNuevoProvinciaCbx.getSelectedIndex());
        String var= UsuarioNuevoCiudadTxt.getText();
        String resultadoV = var.replace(',', '.');
        String direccion1= UsuarioNuevoDireccion1Txt.getText();
        String resultadoD1= direccion1.replace(',', '.');
        String direccion2= UsuarioNuevoDireccion2Txt.getText();
        String resultadoD2= direccion2.replace(',', '.');
        String ciudad= UsuarioNuevoCiudadTxt.getText();
        String resultadoCdad= ciudad.replace(',', '.');
        
         while (apellido.contains("1") || apellido.contains("2")
                || apellido.contains("3") || apellido.contains("4")
                || apellido.contains("5") || apellido.contains("6")
                || apellido.contains("7") || apellido.contains("8")
                || apellido.contains("9") || apellido.contains("0")) {
            JOptionPane.showMessageDialog(null, "El apellido no debe contener números. "
                    + "Ingréselo de nuevo.");
                UsuarioNuevoApellidoTxt.setText("");
                apellido= UsuarioNuevoApellidoTxt.getText();
        }
        while (nombre.contains("1") || nombre.contains("2")
                || nombre.contains("3") || nombre.contains("4")
                || nombre.contains("5") || nombre.contains("6")
                || nombre.contains("7") || nombre.contains("8")
                || nombre.contains("9") || nombre.contains("0")) {
            JOptionPane.showMessageDialog(null, "El nombre no debe contener números. Ingréselo de nuevo");
            UsuarioNuevoNombreTxt.setText("");
            nombre =  UsuarioNuevoNombreTxt.getText();
        }
        
       
         while (segundoNombre.contains("1") || segundoNombre.contains("2")
                || segundoNombre.contains("3") || segundoNombre.contains("4")
                || segundoNombre.contains("5") || segundoNombre.contains("6")
                || segundoNombre.contains("7") || segundoNombre.contains("8")
                || segundoNombre.contains("9") || segundoNombre.contains("0")) {
            JOptionPane.showMessageDialog(null, "El segundo nombre no debe contener números. Ingréselo de nuevo");
            UsuarioNuevoSegundoNombreTxt.setText("");
            segundoNombre= UsuarioNuevoSegundoNombreTxt.getText();
        }
        boolean done = false;
        int telefono = 0;
        String telefonoString;
         do {
            telefonoString= (UsuarioNuevoTelefonoTxt.getText());
            
            try {
                
               if(telefonoString.length() == 8) {
                    telefono = Integer.parseInt(telefonoString);
                    done = true;
                }else{
                    JOptionPane.showMessageDialog(null, "Error al ingresar el teléfono, ocho digitos son requeridos.");
                    UsuarioNuevoTelefonoTxt.setText("00000000");
                    telefonoString= (UsuarioNuevoTelefonoTxt.getText());
                }
            
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Error al ingresar el teléfono, solo escriba números, no letras.");
                UsuarioNuevoTelefonoTxt.setText("00000000");
                telefonoString= (UsuarioNuevoTelefonoTxt.getText());
            }
        } 
          while (!done);
        
        boolean corregir = true;
        String correoElectronico = "";
        
        while(corregir) {
            
            correoElectronico = UsuarioNuevoEmailTxt.getText();
            
            if(correoElectronico.contains("@") && correoElectronico.contains(".")){
                corregir = false;
            }else{
                JOptionPane.showMessageDialog(null, "Error: Formato de correo no valido", "Error", JOptionPane.ERROR_MESSAGE);
                UsuarioNuevoEmailTxt.setText("@ .com");
                UsuarioNuevoEmailTxt.getText();
            }
            
        }
        
        String resultadoC = correoElectronico.replace(',', '.'); 
        String resultadoN = apellido.replace(',', '.');
        String resultadoA = nombre.replace(',', '.');
        String resultadoSN = segundoNombre.replace(',', '.');
       //  return resultadoN; ESTO ME DA ERROR AL PONERLO, SE NECESITA??
       // return genero;
      // return resultadoA
       //  return telefono;
    }//GEN-LAST:event_UsuarioNuevoGuardarBtnMouseClicked

    private void UsuarioNuevoLimpiarCasillasBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioNuevoLimpiarCasillasBtnMouseClicked
        // Al darle click a borrar se limpian los datos que se escribieron.
        UsuarioNuevoIDUsuarioTxt.setText("");
        UsuarioNuevoNombreTxt.setText("");
        UsuarioNuevoSegundoNombreTxt.setText("");
        UsuarioNuevoApellidoTxt.setText("");
        UsuarioNuevoTelefonoTxt.setText("");
        UsuarioNuevoCiudadTxt.setText("");
        UsuarioNuevoDireccion1Txt.setText("");
        UsuarioNuevoDireccion2Txt.setText("");
        UsuarioNuevoEmailTxt.setText("");
        UsuarioNuevoGeneroCbx.setSelectedIndex(0);
        UsuarioNuevoTipoTelefonoCbx.setSelectedIndex(0);
        UsuarioNuevoProvinciaCbx.setSelectedIndex(0);
    }//GEN-LAST:event_UsuarioNuevoLimpiarCasillasBtnMouseClicked

    private void UsuarioNuevoGuardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioNuevoGuardarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioNuevoGuardarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRegistrarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UsuarioNuevoApellidoTxt;
    private javax.swing.JTextField UsuarioNuevoCiudadTxt;
    private javax.swing.JTextField UsuarioNuevoDireccion1Txt;
    private javax.swing.JTextField UsuarioNuevoDireccion2Txt;
    private javax.swing.JTextField UsuarioNuevoEmailTxt;
    private javax.swing.JComboBox<String> UsuarioNuevoGeneroCbx;
    private javax.swing.JButton UsuarioNuevoGuardarBtn;
    private javax.swing.JTextField UsuarioNuevoIDUsuarioTxt;
    private javax.swing.JButton UsuarioNuevoLimpiarCasillasBtn;
    private javax.swing.JTextField UsuarioNuevoNombreTxt;
    private javax.swing.JComboBox<String> UsuarioNuevoProvinciaCbx;
    private javax.swing.JTextField UsuarioNuevoSegundoNombreTxt;
    private javax.swing.JTextField UsuarioNuevoTelefonoTxt;
    private javax.swing.JComboBox<String> UsuarioNuevoTipoTelefonoCbx;
    private javax.swing.JButton UsuarioNuevoVolverAlMenuPrincipalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
