/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fundamentosproyectofinal;

/**
 *
 * @author Karla
 */
public class InterfazConsultarInformacion extends javax.swing.JFrame {

    /**
     * Creates new form InterfazConsultarInformacion
     */
    public InterfazConsultarInformacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ConsultarInformacionUsuarioBtn = new javax.swing.JButton();
        ConsultarInformacionPeliculasBtn = new javax.swing.JButton();
        ConsultarInformacionVolverAPaginaPrincipalBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONSULTAR INFORMACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        ConsultarInformacionUsuarioBtn.setText("Consultar información de usuario");
        ConsultarInformacionUsuarioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarInformacionUsuarioBtnMouseClicked(evt);
            }
        });
        ConsultarInformacionUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarInformacionUsuarioBtnActionPerformed(evt);
            }
        });

        ConsultarInformacionPeliculasBtn.setText("Consultar información de películas");
        ConsultarInformacionPeliculasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarInformacionPeliculasBtnMouseClicked(evt);
            }
        });
        ConsultarInformacionPeliculasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarInformacionPeliculasBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ConsultarInformacionUsuarioBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ConsultarInformacionPeliculasBtn)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ConsultarInformacionPeliculasBtn, ConsultarInformacionUsuarioBtn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(ConsultarInformacionUsuarioBtn)
                .addGap(18, 18, 18)
                .addComponent(ConsultarInformacionPeliculasBtn)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        ConsultarInformacionVolverAPaginaPrincipalBtn.setText("Volver a la página principal");
        ConsultarInformacionVolverAPaginaPrincipalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarInformacionVolverAPaginaPrincipalBtnMouseClicked(evt);
            }
        });
        ConsultarInformacionVolverAPaginaPrincipalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarInformacionVolverAPaginaPrincipalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConsultarInformacionVolverAPaginaPrincipalBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ConsultarInformacionVolverAPaginaPrincipalBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarInformacionUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarInformacionUsuarioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarInformacionUsuarioBtnActionPerformed

    private void ConsultarInformacionPeliculasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarInformacionPeliculasBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarInformacionPeliculasBtnActionPerformed

    private void ConsultarInformacionUsuarioBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarInformacionUsuarioBtnMouseClicked
        // con este codigo vamos a la ventana de buscar usuario
        InterfazBuscarUsuario buscarUsuario= new InterfazBuscarUsuario();
        buscarUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConsultarInformacionUsuarioBtnMouseClicked

    private void ConsultarInformacionPeliculasBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarInformacionPeliculasBtnMouseClicked
        // con este codigo vamos a la ventana de buscar peliculas y cerramos esta
        InterfazBuscarPelicula buscarPelicula= new InterfazBuscarPelicula();
        buscarPelicula.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConsultarInformacionPeliculasBtnMouseClicked

    private void ConsultarInformacionVolverAPaginaPrincipalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarInformacionVolverAPaginaPrincipalBtnMouseClicked
          // con este codigo volvemos al menu principal y cerramos la ventana actual
        InterfazMenuPrincipal menuPrincipal= new  InterfazMenuPrincipal();
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConsultarInformacionVolverAPaginaPrincipalBtnMouseClicked

    private void ConsultarInformacionVolverAPaginaPrincipalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarInformacionVolverAPaginaPrincipalBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarInformacionVolverAPaginaPrincipalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultarInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazConsultarInformacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultarInformacionPeliculasBtn;
    private javax.swing.JButton ConsultarInformacionUsuarioBtn;
    private javax.swing.JButton ConsultarInformacionVolverAPaginaPrincipalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
