/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fundamentosproyectofinal;

import java.awt.HeadlessException;

/**
 *
 * @author Karla
 */
public class InterfazEditarPelicula extends javax.swing.JFrame {

    Menus menuEnInterfaz = new Menus();
    InteraccionConCSV interaccionCSV=  new InteraccionConCSV ();
    public static final String SEPARADOR = ",";
    Interaccion interaccion= new Interaccion();
    Miscelaneos miscelaneos= new Miscelaneos();
    
    public InterfazEditarPelicula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EditarPeliculaIDPeliculaTxt = new javax.swing.JTextField();
        EditarPeliculaBuscarBtn = new javax.swing.JButton();
        EditarPeliculaLimpiarBtn = new javax.swing.JButton();
        EditarPeliculaVolverAlMenuPrincipalBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Película", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setText("ID Película:");

        EditarPeliculaIDPeliculaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPeliculaIDPeliculaTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(EditarPeliculaIDPeliculaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditarPeliculaIDPeliculaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        EditarPeliculaBuscarBtn.setText("Buscar");
        EditarPeliculaBuscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarPeliculaBuscarBtnMouseClicked(evt);
            }
        });
        EditarPeliculaBuscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPeliculaBuscarBtnActionPerformed(evt);
            }
        });

        EditarPeliculaLimpiarBtn.setText("Limpiar");
        EditarPeliculaLimpiarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarPeliculaLimpiarBtnMouseClicked(evt);
            }
        });
        EditarPeliculaLimpiarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPeliculaLimpiarBtnActionPerformed(evt);
            }
        });

        EditarPeliculaVolverAlMenuPrincipalBtn.setText("Volver al menú principal");
        EditarPeliculaVolverAlMenuPrincipalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarPeliculaVolverAlMenuPrincipalBtnMouseClicked(evt);
            }
        });
        EditarPeliculaVolverAlMenuPrincipalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPeliculaVolverAlMenuPrincipalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(EditarPeliculaBuscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditarPeliculaLimpiarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditarPeliculaVolverAlMenuPrincipalBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarPeliculaBuscarBtn)
                    .addComponent(EditarPeliculaLimpiarBtn)
                    .addComponent(EditarPeliculaVolverAlMenuPrincipalBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditarPeliculaBuscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPeliculaBuscarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarPeliculaBuscarBtnActionPerformed

    private void EditarPeliculaIDPeliculaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPeliculaIDPeliculaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarPeliculaIDPeliculaTxtActionPerformed

    private void EditarPeliculaVolverAlMenuPrincipalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPeliculaVolverAlMenuPrincipalBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarPeliculaVolverAlMenuPrincipalBtnActionPerformed

    private void EditarPeliculaVolverAlMenuPrincipalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarPeliculaVolverAlMenuPrincipalBtnMouseClicked
        // con este codigo volvemos al menu principal y cerramos la ventana actual
        InterfazMenuPrincipal menuPrincipal= new  InterfazMenuPrincipal();
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditarPeliculaVolverAlMenuPrincipalBtnMouseClicked

    private void EditarPeliculaBuscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarPeliculaBuscarBtnMouseClicked
         int idBuscar;
        
        String [] info;
        String [] infoTemp;
        boolean done;

        try {

            idBuscar = Integer.parseInt(EditarPeliculaIDPeliculaTxt.getText());

            info = interaccionCSV.buscarPelicula(String.valueOf(idBuscar));
            
            if(info != null){
            
                infoTemp = interaccion.editorPelicula (info);
                
                if(interaccionCSV.actualizarDatosPelicula(infoTemp, String.valueOf(idBuscar))){
                    
                    miscelaneos.actualizacionExitosa();
                    
                }else{
                    
                    miscelaneos.actualizacionSinExito();
                    
                }
                
            }else{
                
                miscelaneos.infoUsuarioInexistente();
                
            }

        }catch(HeadlessException | NumberFormatException error2){

            miscelaneos.mensajeErrorValorNuloONoNumerico();

        }
    }//GEN-LAST:event_EditarPeliculaBuscarBtnMouseClicked

    private void EditarPeliculaLimpiarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPeliculaLimpiarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarPeliculaLimpiarBtnActionPerformed

    private void EditarPeliculaLimpiarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarPeliculaLimpiarBtnMouseClicked
        // con esto se limpiar
        EditarPeliculaIDPeliculaTxt.setText("");
    }//GEN-LAST:event_EditarPeliculaLimpiarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazEditarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazEditarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazEditarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazEditarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazEditarPelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarPeliculaBuscarBtn;
    private javax.swing.JTextField EditarPeliculaIDPeliculaTxt;
    private javax.swing.JButton EditarPeliculaLimpiarBtn;
    private javax.swing.JButton EditarPeliculaVolverAlMenuPrincipalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
