/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fundamentosproyectofinal;

/**
 *
 * @author Karla
 */
public class InterfazMenuUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form InterfazMenuUsuarios
     */
    public InterfazMenuUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuUsuariosIngresarNuevoUsuarioBtn = new javax.swing.JButton();
        MenuUsuariosEditarUsuarioBtn = new javax.swing.JButton();
        MenuUsuariosVolverAPaginaPrincipalBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menú de usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        MenuUsuariosIngresarNuevoUsuarioBtn.setText("Ingresar nuevo usuario");
        MenuUsuariosIngresarNuevoUsuarioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuUsuariosIngresarNuevoUsuarioBtnMouseClicked(evt);
            }
        });
        MenuUsuariosIngresarNuevoUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsuariosIngresarNuevoUsuarioBtnActionPerformed(evt);
            }
        });

        MenuUsuariosEditarUsuarioBtn.setText("Editar usuario");
        MenuUsuariosEditarUsuarioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuUsuariosEditarUsuarioBtnMouseClicked(evt);
            }
        });
        MenuUsuariosEditarUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsuariosEditarUsuarioBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuUsuariosIngresarNuevoUsuarioBtn)
                    .addComponent(MenuUsuariosEditarUsuarioBtn))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {MenuUsuariosEditarUsuarioBtn, MenuUsuariosIngresarNuevoUsuarioBtn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(MenuUsuariosIngresarNuevoUsuarioBtn)
                .addGap(42, 42, 42)
                .addComponent(MenuUsuariosEditarUsuarioBtn)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        MenuUsuariosVolverAPaginaPrincipalBtn.setText("Volver a la página principal");
        MenuUsuariosVolverAPaginaPrincipalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuUsuariosVolverAPaginaPrincipalBtnMouseClicked(evt);
            }
        });
        MenuUsuariosVolverAPaginaPrincipalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsuariosVolverAPaginaPrincipalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MenuUsuariosVolverAPaginaPrincipalBtn)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuUsuariosVolverAPaginaPrincipalBtn)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuUsuariosIngresarNuevoUsuarioBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUsuariosIngresarNuevoUsuarioBtnMouseClicked
        //con eset codigo vamos a la ventana de Ingresar nuevo usuario y cerramos esta
        InterfazRegistrarClientes registrarClientes= new InterfazRegistrarClientes();
        registrarClientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuUsuariosIngresarNuevoUsuarioBtnMouseClicked

    private void MenuUsuariosEditarUsuarioBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUsuariosEditarUsuarioBtnMouseClicked
        // con este codigo vamos a la ventana de editar Usuarios 
        InterfazEditarUsuario editarUsuario= new InterfazEditarUsuario();
        editarUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuUsuariosEditarUsuarioBtnMouseClicked

    private void MenuUsuariosIngresarNuevoUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsuariosIngresarNuevoUsuarioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuUsuariosIngresarNuevoUsuarioBtnActionPerformed

    private void MenuUsuariosEditarUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsuariosEditarUsuarioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuUsuariosEditarUsuarioBtnActionPerformed

    private void MenuUsuariosVolverAPaginaPrincipalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsuariosVolverAPaginaPrincipalBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuUsuariosVolverAPaginaPrincipalBtnActionPerformed

    private void MenuUsuariosVolverAPaginaPrincipalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUsuariosVolverAPaginaPrincipalBtnMouseClicked
        // con este codigo volvemos al menu principal y cerramos la ventana actual
        InterfazMenuPrincipal menuPrincipal= new  InterfazMenuPrincipal();
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuUsuariosVolverAPaginaPrincipalBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMenuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMenuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMenuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMenuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMenuUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuUsuariosEditarUsuarioBtn;
    private javax.swing.JButton MenuUsuariosIngresarNuevoUsuarioBtn;
    private javax.swing.JButton MenuUsuariosVolverAPaginaPrincipalBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
