/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fundamentosproyectofinal;

/**
 *
 * @author Karla
 */
public class InterfazMenuPeliculas extends javax.swing.JFrame {

    /**
     * Creates new form InterfazMenuPeliculas
     */
    public InterfazMenuPeliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuPeliculasIngresarNuevaPelicula = new javax.swing.JButton();
        MenuPeliculasEditarInformacionPelicula = new javax.swing.JButton();
        MenuPeliculasVolverAlMenuPrincipal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENÚ DE PELÍCULAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        MenuPeliculasIngresarNuevaPelicula.setText("Ingresar nueva película");
        MenuPeliculasIngresarNuevaPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPeliculasIngresarNuevaPeliculaMouseClicked(evt);
            }
        });
        MenuPeliculasIngresarNuevaPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPeliculasIngresarNuevaPeliculaActionPerformed(evt);
            }
        });

        MenuPeliculasEditarInformacionPelicula.setText("Editar información de película");
        MenuPeliculasEditarInformacionPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPeliculasEditarInformacionPeliculaActionPerformed(evt);
            }
        });

        MenuPeliculasVolverAlMenuPrincipal.setText("Volver al menú principal");
        MenuPeliculasVolverAlMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPeliculasVolverAlMenuPrincipalMouseClicked(evt);
            }
        });
        MenuPeliculasVolverAlMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPeliculasVolverAlMenuPrincipalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MenuPeliculasVolverAlMenuPrincipal)
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenuPeliculasIngresarNuevaPelicula)
                            .addComponent(MenuPeliculasEditarInformacionPelicula)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {MenuPeliculasEditarInformacionPelicula, MenuPeliculasIngresarNuevaPelicula});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(MenuPeliculasIngresarNuevaPelicula)
                .addGap(18, 18, 18)
                .addComponent(MenuPeliculasEditarInformacionPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(MenuPeliculasVolverAlMenuPrincipal)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPeliculasIngresarNuevaPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPeliculasIngresarNuevaPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPeliculasIngresarNuevaPeliculaActionPerformed

    private void MenuPeliculasVolverAlMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPeliculasVolverAlMenuPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPeliculasVolverAlMenuPrincipalActionPerformed

    private void MenuPeliculasIngresarNuevaPeliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPeliculasIngresarNuevaPeliculaMouseClicked
        // con este codigo vamos a la ventana de  Ingresar nueva pelicula y se cierra esta
        InterfazRegistrarPeliculaNueva registrarPelicula= new InterfazRegistrarPeliculaNueva();
        registrarPelicula.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuPeliculasIngresarNuevaPeliculaMouseClicked

    private void MenuPeliculasEditarInformacionPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPeliculasEditarInformacionPeliculaActionPerformed
        // con este codigo vamos a la ventana de editar pelicula y cerramos esta
        InterfazEditarPelicula editarPelicula= new InterfazEditarPelicula();
        editarPelicula.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuPeliculasEditarInformacionPeliculaActionPerformed

    private void MenuPeliculasVolverAlMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPeliculasVolverAlMenuPrincipalMouseClicked
        // con este codigo volvemos al menu principal y cerramos la ventana actual
        InterfazMenuPrincipal menuPrincipal= new  InterfazMenuPrincipal();
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuPeliculasVolverAlMenuPrincipalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMenuPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMenuPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMenuPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMenuPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMenuPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuPeliculasEditarInformacionPelicula;
    private javax.swing.JButton MenuPeliculasIngresarNuevaPelicula;
    private javax.swing.JButton MenuPeliculasVolverAlMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
