/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fundamentosproyectofinal;

import java.awt.HeadlessException;

/**
 *
 * @author Karla
 */
public class InterfazEditarUsuario extends javax.swing.JFrame {

    Menus menuEnInterfaz = new Menus();
    InteraccionConCSV interaccionCSV=  new InteraccionConCSV ();
    public static final String SEPARADOR = ",";
    Interaccion interaccion= new Interaccion();
    Miscelaneos miscelaneos= new Miscelaneos();
    
    public InterfazEditarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        EditarUsuarioBuscarBtn = new javax.swing.JButton();
        EditarUsuarioLimpiarBtn = new javax.swing.JButton();
        EditarUsuarioVolveralMenuPrincipalBtn = new javax.swing.JButton();
        EditarUsuarioIDUsuarioTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("EDITAR USUARIO");

        jLabel16.setText("ID Usuario:");

        EditarUsuarioBuscarBtn.setText("Buscar");
        EditarUsuarioBuscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarUsuarioBuscarBtnMouseClicked(evt);
            }
        });

        EditarUsuarioLimpiarBtn.setText("Limpiar");
        EditarUsuarioLimpiarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarUsuarioLimpiarBtnMouseClicked(evt);
            }
        });

        EditarUsuarioVolveralMenuPrincipalBtn.setText("Volver al menú principal");
        EditarUsuarioVolveralMenuPrincipalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarUsuarioVolveralMenuPrincipalBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EditarUsuarioIDUsuarioTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(EditarUsuarioBuscarBtn)
                                .addGap(18, 18, 18)
                                .addComponent(EditarUsuarioLimpiarBtn)))
                        .addGap(18, 18, 18)
                        .addComponent(EditarUsuarioVolveralMenuPrincipalBtn))
                    .addComponent(jLabel1))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditarUsuarioIDUsuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarUsuarioBuscarBtn)
                    .addComponent(EditarUsuarioLimpiarBtn)
                    .addComponent(EditarUsuarioVolveralMenuPrincipalBtn))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EditarUsuarioBuscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarUsuarioBuscarBtnMouseClicked
        int idBuscar;
        
        String [] info;
        String [] infoTemp;
        boolean done;

        try {

            idBuscar = Integer.parseInt(EditarUsuarioIDUsuarioTxt.getText());

            info = interaccionCSV.buscarUsuario(String.valueOf(idBuscar));
            
            if(info != null){
            
                infoTemp = interaccion.editorCliente(info);
                
                if(interaccionCSV.actualizarDatosUsuario(infoTemp, String.valueOf(idBuscar))){
                    
                    miscelaneos.actualizacionExitosa();
                    
                }else{
                    
                    miscelaneos.actualizacionSinExito();
                    
                }
                
            }else{
                
                miscelaneos.infoUsuarioInexistente();
                
            }

        }catch(HeadlessException | NumberFormatException error2){

            miscelaneos.mensajeErrorValorNuloONoNumerico();

        }
    }//GEN-LAST:event_EditarUsuarioBuscarBtnMouseClicked

    private void EditarUsuarioLimpiarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarUsuarioLimpiarBtnMouseClicked
        EditarUsuarioIDUsuarioTxt.setText("");
    }//GEN-LAST:event_EditarUsuarioLimpiarBtnMouseClicked

    private void EditarUsuarioVolveralMenuPrincipalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarUsuarioVolveralMenuPrincipalBtnMouseClicked
        InterfazMenuPrincipal menuPrincipal= new  InterfazMenuPrincipal();
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditarUsuarioVolveralMenuPrincipalBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazEditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarUsuarioBuscarBtn;
    private javax.swing.JTextField EditarUsuarioIDUsuarioTxt;
    private javax.swing.JButton EditarUsuarioLimpiarBtn;
    private javax.swing.JButton EditarUsuarioVolveralMenuPrincipalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    // End of variables declaration//GEN-END:variables
}
